#!/bin/bash

# setup fd-3 to point to the original stdout
exec 3>&1
# setup fd-4 to point to the original stderr
exec 4>&2

# get the prefix from SUPERVISOR_PROCESS_NAME environment variable
printf -v PREFIX "%-25.25s" "${SUPERVISOR_PROCESS_NAME}"

# function to prefix the output
prefix_output() {
    while IFS= read -r line; do
        echo "${PREFIX} | ${line}"
    done
}

# reassign stdout and stderr to a preprocessed and redirected to the original stdout/stderr (3 and 4) we have created earlier
exec 1> >(prefix_output >&3)
exec 2> >(prefix_output >&4)

# from here on everything that outputs to stdout/stderr will be go through the prefix_output function
exec "$@"
